apiVersion: "v1"
kind: "BuildConfig"
metadata:
    name: "item-aggregator"
spec:
    resources:
        limits:
            cpu: '4'
            memory: 4Gi
    source:
        git: 
            uri: "https://github.com/jbcodeforce/eda-kconnect-lab.git"
            ref: "master"
            contextDir: "item-aggregator"
